version: '3.8'

services:
  backend:
    build:
      context: ./Courier
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./Courier:/code
    depends_on:
      - db

  frontend:
    build:
      context: ./couriers
    command: npm start
    ports:
      - "3000:3000"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: courier_user
      POSTGRES_PASSWORD: courier_pass
      POSTGRES_DB: courier_db
    ports:
      - "5432:5432"
