FROM python:3.11-slim

WORKDIR /workspace

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . /workspace

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
