FROM python:3.9-slim
WORKDIR /workspace

RUN apt-get update && apt-get install -y curl && \
    pip install --upgrade pip

COPY requirements.txt .

RUN pip install --upgrade pip
RUN if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
EXPOSE 8000