# Generated by Django 5.0.6 on 2024-11-26 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0002_booking_pickup'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomsClearanceExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clearance_status', models.CharField(choices=[('Pending', 'Pending'), ('Cleared', 'Cleared'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('export_documentation', models.TextField(help_text='List of required export documents')),
                ('customs_officer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('clearance_date', models.DateField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='export_clearance', to='couriers.booking')),
            ],
        ),
        migrations.CreateModel(
            name='CustomsClearanceImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clearance_status', models.CharField(choices=[('Pending', 'Pending'), ('Cleared', 'Cleared'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('import_documentation', models.TextField(help_text='List of required import documents')),
                ('customs_officer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('clearance_date', models.DateField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='import_clearance', to='couriers.booking')),
            ],
        ),
    ]
