# Generated by Django 5.0.6 on 2024-11-26 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0003_customsclearanceexport_customsclearanceimport'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastMileDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_status', models.CharField(choices=[('In Transit', 'In Transit'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], default='In Transit', max_length=50)),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_address', models.CharField(max_length=255)),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='last_mile_delivery', to='couriers.booking')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
